services:
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build -- --configuration production
    staticPublishPath: ./dist/angular-10-boilerplate/browser
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html