services:
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist/angular-10-boilerplate
    envVars:
      - key: NODE_VERSION
        value: 18.15.0