services:
  # Backend API service
  - type: web
    name: user-management-api
    runtime: node
    plan: free
    rootDir: Node-js-MySQL-BoilerPlate
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false  # Prompt for this value during deployment
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /api/*
        destination: /*

 # Frontend web app
  - type: web
    name: user-management-frontend
    runtime: static
    buildCommand: ./render-build.sh
    staticPublishPath: ./dist/angular-signup-verification-boilerplate
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html